### ISSUE TITLE
Wird der Kesselzustand abgefragt?

### ISSUE THREAD

**Issue by weindler** [TA2k/ioBroker.froeling#4]
Zuerst mal Danke für deine Mühe, toller Adapter,

kann es sein, daß sich der Kesselzustand eventuell nicht ändert.

Boiler State - String List Values.

Set Value steht bei mir auf "Null"

Value Key ist aktuell 19 (Betriebsbereit) obwohl Kessel im Zustand Heizen (3) befindet, ich konnte auch bisher sonst keine Änderung des Kesselzustandes feststellen, obwohl ich den value Key in der Vis abfrage mit den verschiedenen werten, gebe ich sie als Testwerte im Editor der Vis ein, funktionieren sie.

Vielleicht wird der Datenpunkt einfach nicht aktualisiert.

Schon mal vorab danke

**Comment by TA2k** [comment]
Mal alle Datenpunkte löschen und adapter Neustarten kommen die Datenpunkte dann aktuell?

**Comment by weindler** [comment]
Ok danke, ich habe es mal so gemacht, mal schauen beim nächsten Start des Ofens ob es angezeigt wird. Obwohl daß die Datenpunkte aktuell waren, nur im Boiler State wo er das Zünden, stoke leeren usw anzeigt diese Daatenpunkte werden nicht in das Value übertragen.

**Comment by weindler** [comment]
die Datenpunkte werden definitiv nicht aktualisiert, mein Kessel fing wieder das Heizen an,  froeling.0.46035.boilerState.valueKey stand auf "Betriebsbereit", dann änderte sich der Status auf Heizen, es wurden bei einem Aktuialisierungsintervall der Instanz von 1 Minute die Datenpunkte nicht aktualisiert.

Als ich dann den kompletten Datenbaum Froeling gelöscht habe und dann wieder die INstanz gestartet habe, stand der Datenpunkt auf Heizen, so wie es auch richtig ist.

Nach Beendigung des Heizvorgangs und den weiteren Vorgängen steht der Kessel nun wieder in COnnect auf Betriebsbereit, im Iobroker steht Heizen.

Mache ich da was falsch?

**Comment by TA2k** [comment]
Nein der Adapter anscheinend

**Comment by weindler** [comment]
OK, wenn ich dir beim Testen helfen kann, tue ich gerne, melde dich einfach, denn wie gesagt die Heizung ist jetzt bei mir ein, bei diesen Temperaturen, und die verschiedenen Sachen online zu haben wäre auch sinnvoll, denn da wäre die "Störung" auch gleich ersichtlich, denn aktuell werden diese Datenpunkte nicht aktualisiert, außer man startet die Instanz neu.

**Comment by TA2k** [comment]
Ich bräuchte wahrscheinlich Zugangsdaten via mail um zu sehen was da genau passiert
tombox2020@gmail.com

**Comment by weindler** [comment]
Nach dem Update auf die 0.0.6 funktioniert das automatische Übernehmen der Punkte, danke, hiermit wird das Issue geschlossen.

**Comment by weindler** [comment]
geschlossen
