### ISSUE TITLE
SetValue is not working anymore

### ISSUE THREAD

**Issue by tonez18** [TA2k/ioBroker.froeling#6]
**Describe the bug**  
After clearing the object tree and updating the adapter to 0.0.6 my custom script for filling the boiler with pellets is not working anymore. 

Breaking changes or bug? :) 

Following command results in a warning message
`setState('froeling.0.45253.componentList.Austragung-Austragung.startFirstFilling.setValue', hours+":"+minutes);`

Warning message:
`State "froeling.0.45253.componentList.Austragung-Austragung.startFirstFilling.value.setValue" not found`

**Versions:**  
 - Adapter version: 0.0.6

Thanks for providing this great adapter. Filling the pellets when I'm not at home, without hearing the pellet vacuum cleaner, making my life more comfortable ^^

**Comment by TA2k** [comment]
can you check the component list for Austragung is this still present?

**Comment by tonez18** [comment]
![froeling-issue](https://user-images.githubusercontent.com/12811799/195104749-448cecc2-f555-4ea5-8280-03127ede453c.PNG)

yes, it is

**Comment by tonez18** [comment]
thank you. Seems to be working now :)
