### ISSUE TITLE
froeling.0.XXXXX.systemInfo.hoursInPelletMode aktualisieren

### ISSUE THREAD

**Issue by weindler** [TA2k/ioBroker.froeling#7]
Hi, danke für den Adapter, eine Frage könntest du bitte den Datenpunkt

froeling.0.XXXXX.systemInfo.hoursInPelletMode

öfters aktualisieren lassen, ich denke es wäre ein wichtiger Wert. 

In Connect wird er aktualisiert, im Adapter aber nur nach Neustart. Danke

**Comment by TA2k** [comment]
GitHub version aktualisiert jetzt alle 12h die werte

**Comment by weindler** [comment]
Danke, github version 0.0.7 installiert, ohne auffälligkeiten, datenpunkt wurde aktualisiert, ich denke dann kann man das issue schließen, danke dir für die schnelle Ausführung, top job

**Comment by weindler** [comment]
Jetzt werden die normalen Datenpunkte nicht mehr aktualisiert oder auch erst in 12h

**Comment by TA2k** [comment]
Sehe direkt nichts. Bitte mal die Instanz in debug log setzen und schauen ob Daten im interval ankommen

**Comment by weindler** [comment]
Habe heute früh iob neu gestartet zwecks updates und so, jetzt funktioniert es, ich halte das mal aber trotzdem im Auge.

**Comment by weindler** [comment]
So, hier ein Bild, sagt mehr als 1000 Worte, der Datenpunkt froeling.0.XXXXX.systemInfo.hoursInPelletMode wird auf jeden Fall nicht alle 12h aktualisiert. Letzte Aktualisierung 14.1. und das war da, wo ich iob neu gestartet habe.

![Heizstunden](https://user-images.githubusercontent.com/41335851/212710957-f3d0d616-5d63-4dd7-8221-a9b78e650683.jpg)

**Comment by TA2k** [comment]
kannst du nochmal installieren und checken ob 0.0.8 installiert ist
dann debug log aktivieren und mir ein log nach 13h schicken
tombox2020@gmail.com

**Comment by TA2k** [comment]
wie gesagt ein debug log via mail wäre hilfreich

**Comment by weindler** [comment]
Habe dir an deine Mail das log gesendet, danke für deine Arbeit.

**Comment by TA2k** [comment]
Bitte nochmal installieren und testen

**Comment by weindler** [comment]
Ok, erledigt, es wird jetzt nach der vorgegebenen Zeit aktualisiert, jetzt schaue ich mal ob das mit den 12 H klappt bei den Heizstunden. Danke dir

**Comment by weindler** [comment]
Bis jetzt schaut es gut aus, auch die Heizzeiten werden nach 12h aktualisiert. Passt, danke dir.

**Comment by weindler** [comment]
Kann man schließen.
